services:
  userservice:
    container_name: bookhub-userservice-debug
    image: bookhub/userservice-debug
    build:
      context: ./services/user-service
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5002:8002
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
