networks:
  bookhub-network:
    name: ${NETWORK_NAME}
    driver: bridge

services:
  bookservice-dev-db:
    container_name: ${BOOK_SERVICE_DB_CONTAINER_NAME}
    image: postgres:16
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: books
    ports:
      - "6003:5432"
    volumes:
      - bookservice_data:/var/lib/postgresql/data
    networks:
      - bookhub-network

volumes:
  bookservice_data:
