"""added-isDeleted-flag-on-book

Revision ID: 6a6da7832f80
Revises: 8292883872ad
Create Date: 2025-08-31 11:34:32.673375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a6da7832f80'
down_revision: Union[str, Sequence[str], None] = '8292883872ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('isDeleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'isDeleted')
    # ### end Alembic commands ###
